# Dependencies
#markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Düzgün Dilsiz
tagline:          'Personal Website'
description:      '<p><a href="mailto:d.dilsiz@unibas.ch">d.dilsiz@unibas.ch</a></p>
                  PhD Student at the <a href="https://www.wwz.unibas.ch">University of Basel</a>, Switzerland.'
url:              https://d-dilsiz.github.io
baseurl:          ""

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde


plugins: [jekyll-paginate]
